WebApplicationMiTiendaMejorada/Controllers/productosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplicationMiTiendaMejorada.Contexto;

namespace WebApplicationMiTiendaMejorada.Controllers
{
    public class productosController : Controller
    {
        private MiTiendaMejoradaEntities db = new MiTiendaMejoradaEntities();

        // GET: productos
        public ActionResult Index()
        {
            var productoes = db.Productoes.Include(p => p.Proveedor);
            return View(productoes.ToList());
        }

        // GET: productos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: productos/Create
        public ActionResult Create()
        {
            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor");
            return View();
        }

        // POST: productos/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_producto,producto_nombre,producto_precio,producto_cantidad,producto_descripcion,id_proveedor")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Productoes.Add(producto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor", producto.id_proveedor);
            return View(producto);
        }

        // GET: productos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor", producto.id_proveedor);
            return View(producto);
        }

        // POST: productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_producto,producto_nombre,producto_precio,producto_cantidad,producto_descripcion,id_proveedor")] Producto producto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor", producto.id_proveedor);
            return View(producto);
        }

        // GET: productos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productoes.Find(id);
            db.Productoes.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        // GET: productos/Edit/5
        public ActionResult ventaProductos(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productoes.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor", producto.id_proveedor);
            return View(producto);
        }

        // POST: productos/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ventaProductos([Bind(Include = "id_producto,producto_nombre,producto_precio,producto_cantidad,producto_descripcion,id_proveedor")] Producto producto, int cantidadProducto, int precioVenta)
        {
            if (ModelState.IsValid)
            {
                Venta ventas = new Venta();
                ventas.id_ventas++;
                ventas.venta_total = precioVenta;

                db.Ventas.Add(ventas);

                producto.producto_cantidad = producto.producto_cantidad - cantidadProducto;
                db.Entry(producto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.id_proveedor = new SelectList(db.Proveedors, "id_proveedor", "nombre_proveedor", producto.id_proveedor);
            return View(producto);
        }


        public ActionResult precioDeVenta(int id_Producto, int cantidad_producto)
        {
            var valorProducto = (from producto in db.Productoes
                                 where producto.id_producto == id_Producto
                                 select producto.producto_precio).FirstOrDefault();

            int valor = int.Parse(valorProducto.ToString());

            return Content((valor * cantidad_producto).ToString());
        }
    }

}

WebApplicationMiTiendaMejorada/Views/productos/Create.cshtml
@model WebApplicationMiTiendaMejorada.Contexto.Producto

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.producto_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_proveedor, "id_proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_proveedor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplicationMiTiendaMejorada/Views/productos/Delete.cshtml
@model WebApplicationMiTiendaMejorada.Contexto.Producto

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.producto_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proveedor.nombre_proveedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proveedor.nombre_proveedor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplicationMiTiendaMejorada/Views/productos/Details.cshtml
@model WebApplicationMiTiendaMejorada.Contexto.Producto

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.producto_nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_precio)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_cantidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_cantidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.producto_descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.producto_descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Proveedor.nombre_proveedor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Proveedor.nombre_proveedor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id_producto }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplicationMiTiendaMejorada/Views/productos/Edit.cshtml
@model WebApplicationMiTiendaMejorada.Contexto.Producto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_producto)

        <div class="form-group">
            @Html.LabelFor(model => model.producto_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.producto_descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.producto_descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.producto_descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.id_proveedor, "id_proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id_proveedor", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebApplicationMiTiendaMejorada/Views/productos/Index.cshtml
@model IEnumerable<WebApplicationMiTiendaMejorada.Contexto.Producto>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.producto_nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.producto_precio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.producto_cantidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.producto_descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Proveedor.nombre_proveedor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.producto_nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.producto_precio)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.producto_cantidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.producto_descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Proveedor.nombre_proveedor)
        </td>
		<td>
			@Html.ActionLink("Vender", "ventaProductos", new { id = item.id_producto }) |
			@Html.ActionLink("Editar", "Edit", new { id = item.id_producto }) |
			@Html.ActionLink("Detalles", "Details", new { id = item.id_producto }) |
			@Html.ActionLink("Eliminar", "Delete", new { id = item.id_producto })
		</td>
    </tr>
}

</table>

WebApplicationMiTiendaMejorada/Views/productos/ventaProductos.cshtml
@model WebApplicationMiTiendaMejorada.Contexto.Producto

@{
    ViewBag.Title = "ventaProductos";
}

<h2>Venta de productos de Mi Tienda Mejorada</h2>
<script src="@Url.Content("~/Scripts/jquery-3.3.1.js")"></script>

<script>

	$(document).ready(function () {
		$('#cantidadProducto').on('input', function () {
			$.ajax({
				data:{cantidad_producto:$('#cantidadProducto').val(),id_Producto:@Model.id_producto},
				type: 'GET',
				url: '@Url.Action("precioDeVenta","productos")',
				success: function (resultado) {

					$('#precioVenta').val(resultado);
				}
			});
		});
	});
</script>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	@Html.HiddenFor(model => model.id_producto)

	<div class="form-group">
		@Html.LabelFor(model => model.producto_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.producto_nombre, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.producto_nombre, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.producto_precio, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.producto_precio, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.producto_precio, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.producto_cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.producto_cantidad, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.producto_cantidad, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.producto_descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.producto_descripcion, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.producto_descripcion, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.id_proveedor, "id_proveedor", htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.DropDownList("id_proveedor", null, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.id_proveedor, "", new { @class = "text-danger" })
		</div>
	</div>




	<div class="form-group">
		<label class="control-label col-md-2">Cantidad de Producto a Vender</label>
		<div class="col-md-10">
			<input type="text" class="form-control" id="cantidadProducto" name="cantidadProducto" placeholder="Cantidad" />
		</div>
	</div>

	<div class="form-group">
		<label class="control-label col-md-2">Precio de Venta</label>
		<div class="col-md-10">
			<input type="text" class="form-control" id="precioVenta" name="precioVenta"  />
		</div>
	</div>




	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<input type="submit" value="Save" class="btn btn-default" />
		</div>
	</div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}